[package]
org = "ballerinax"
name = "sap.jco"
version = "0.3.1"
distribution = "2201.9.0"
authors = ["Ballerina"]
keywords = ["Business Management/ERP", "Cost/Paid", "Vendor/SAP"]
repository = "https://github.com/ballerina-platform/module-ballerinax-sap.jco"
icon = "icon.png"
license = ["Apache-2.0"]


[[platform.java17.dependency]]
groupId = "io.ballerina.lib.sap"
artifactId = "sap.jco-native"
version = "0.3.1-SNAPSHOT"
path = "../native/build/libs/sap.jco-native-0.3.1-SNAPSHOT.jar"

[[platform.java17.dependency]]
path = "../native/libs/sapidoc3.jar"
scope = "provided"
groupId="com.sap"
artifactId="com.sap.conn.idoc"
version="3.1.*"

[[platform.java17.dependency]]
path = "../native/libs/sapjco3.jar"
scope = "provided"
groupId="com.sap"
artifactId="com.sap.conn.jco"
version="3.1.*"

